import { join } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { REPO_ROOT, pluginEntries } from './plugin-discovery.mjs';

// Resolved once, at config load. Anything wrong with the configuration — a
// missing directory, a directory with no entry module, a malformed
// `foreman-plugins.json` — throws here, before a dev server or a build exists.
// That is the guarantee: a configured plugin that is not on disk is a loud
// failure with the path in it, never a tab that quietly does not appear.
const plugins = pluginEntries();

const VIRTUAL_ROSTER = 'virtual:foreman-plugins';
const RESOLVED_ROSTER = '\0' + VIRTUAL_ROSTER;

/**
 * The roster, generated from `foreman-plugins.json`.
 *
 * Static `import` statements, not `import()` and not a runtime lookup: the
 * module graph still contains every plugin at build time, so Rollup resolves
 * and tree-shakes them exactly as it did when the roster was a hand-written
 * list. Only the *list* moved into configuration.
 *
 * `shellFromModule` turns each namespace back into a single shell — see its
 * comment for why the import is a namespace rather than a named binding.
 */
function foremanPlugins() {
  // Anchored on the repo root rather than `import.meta.url`: Vite bundles this
  // config to a temporary file before running it, so the module's own URL is
  // not a stable thing to resolve against.
  const selector = join(REPO_ROOT, 'apps/web/src/foreman/usecases/plugin-module.ts');

  return {
    name: 'foreman-plugins',
    resolveId(id: string) {
      return id === VIRTUAL_ROSTER ? RESOLVED_ROSTER : null;
    },
    load(id: string) {
      if (id !== RESOLVED_ROSTER) return null;

      return [
        '// Generated by the `foreman-plugins` Vite plugin from foreman-plugins.json.',
        `import { shellFromModule } from ${JSON.stringify(selector)};`,
        ...plugins.map((p, i) => `import * as plugin${String(i)} from ${JSON.stringify(p.entry)};`),
        '',
        'export const shells = [',
        ...plugins.map((p, i) => `  shellFromModule(plugin${String(i)}, ${JSON.stringify(p.spec)}),`),
        '];',
        '',
        `export const pluginSources = ${JSON.stringify(plugins.map((p) => p.spec))};`,
        '',
      ].join('\n');
    },
  };
}

// Vite serves files under the workspace root by default. A plugin directory
// outside it (the point of OT-2 — victoria and polymarket move to the omega
// repo next) has to be allow-listed, or dev fails with "outside of Vite serving
// allow list" the moment one of its views is imported. In-repo directories are
// already covered by the default, so only the outsiders are added.
const outOfTreeDirs = [...new Set(plugins.map((p) => p.dir))].filter(
  (dir) => dir !== REPO_ROOT && !dir.startsWith(REPO_ROOT + '/')
);

// The kit, by absolute path.
//
// This is what makes an out-of-tree plugin actually work, and it is not
// optional. Node resolution walks up from the *importing* file, and the
// importing file is in another repository: `import … from
// '@omega-harness/usecase-kit'` inside `../omega/foreman-plugins/victoria`
// resolves against *that* repo's `node_modules`, not this workspace's. It does
// resolve there — the plugin declares the kit as a `file:` dependency so
// editors and `tsc` over there have types — but it would resolve to a second
// copy, and the two copies' `setUseCaseEnv` bags are different objects: the
// host would fill one and every shell would read the other, silently pinning
// each to its declared `baseUrl`. Aliasing the package name (and its `/ui`
// entry) to this workspace's build means there is exactly one kit in the graph
// however far away the plugin lives.
//
// The alias points at the built files rather than the package directory
// because an alias replacement bypasses the `exports` map; naming both entries
// keeps `/ui` working. Consequence, and it is the same one the whole repo
// already lives with: `task build:kit` before anything that reads it.
const KIT_DIR = join(REPO_ROOT, 'packages/usecase-kit');

export default defineConfig({
  plugins: [react(), foremanPlugins()],
  resolve: {
    alias: [
      { find: /^@omega-harness\/usecase-kit$/, replacement: join(KIT_DIR, 'dist/index.js') },
      { find: /^@omega-harness\/usecase-kit\/ui$/, replacement: join(KIT_DIR, 'dist/ui/index.js') },
    ],
    // Same hazard, worse symptom. A plugin repo has its own React installed
    // (its tests render), so a bare `import { useState } from 'react'` in an
    // out-of-tree view would resolve to *that* copy — two Reacts in one page,
    // and every hook in the shell throws "invalid hook call". `dedupe` forces
    // every request for these to resolve from this root.
    dedupe: ['react', 'react-dom'],
  },
  server: {
    port: 5173,
    fs: {
      allow: [REPO_ROOT, ...outOfTreeDirs],
    },
    proxy: {
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
});
