import { join } from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { REPO_ROOT, pluginEntries } from './plugin-discovery.mjs';

// Resolved once, at config load. Anything wrong with the configuration — a
// missing directory, a directory with no entry module, a malformed
// `foreman-plugins.json` — throws here, before a dev server or a build exists.
// That is the guarantee: a configured plugin that is not on disk is a loud
// failure with the path in it, never a tab that quietly does not appear.
const plugins = pluginEntries();

const VIRTUAL_ROSTER = 'virtual:foreman-plugins';
const RESOLVED_ROSTER = '\0' + VIRTUAL_ROSTER;

/**
 * The roster, generated from `foreman-plugins.json`.
 *
 * Static `import` statements, not `import()` and not a runtime lookup: the
 * module graph still contains every plugin at build time, so Rollup resolves
 * and tree-shakes them exactly as it did when the roster was a hand-written
 * list. Only the *list* moved into configuration.
 *
 * `shellFromModule` turns each namespace back into a single shell — see its
 * comment for why the import is a namespace rather than a named binding.
 */
function foremanPlugins() {
  // Anchored on the repo root rather than `import.meta.url`: Vite bundles this
  // config to a temporary file before running it, so the module's own URL is
  // not a stable thing to resolve against.
  const selector = join(REPO_ROOT, 'apps/web/src/foreman/usecases/plugin-module.ts');

  return {
    name: 'foreman-plugins',
    resolveId(id: string) {
      return id === VIRTUAL_ROSTER ? RESOLVED_ROSTER : null;
    },
    load(id: string) {
      if (id !== RESOLVED_ROSTER) return null;

      return [
        '// Generated by the `foreman-plugins` Vite plugin from foreman-plugins.json.',
        `import { shellFromModule } from ${JSON.stringify(selector)};`,
        ...plugins.map((p, i) => `import * as plugin${String(i)} from ${JSON.stringify(p.entry)};`),
        '',
        'export const shells = [',
        ...plugins.map((p, i) => `  shellFromModule(plugin${String(i)}, ${JSON.stringify(p.spec)}),`),
        '];',
        '',
        `export const pluginSources = ${JSON.stringify(plugins.map((p) => p.spec))};`,
        '',
      ].join('\n');
    },
  };
}

// Vite serves files under the workspace root by default. A plugin directory
// outside it (the point of OT-2 — victoria and polymarket move to the omega
// repo next) has to be allow-listed, or dev fails with "outside of Vite serving
// allow list" the moment one of its views is imported. In-repo directories are
// already covered by the default, so only the outsiders are added.
const outOfTreeDirs = [...new Set(plugins.map((p) => p.dir))].filter(
  (dir) => dir !== REPO_ROOT && !dir.startsWith(REPO_ROOT + '/')
);

export default defineConfig({
  plugins: [react(), foremanPlugins()],
  server: {
    port: 5173,
    fs: {
      allow: [REPO_ROOT, ...outOfTreeDirs],
    },
    proxy: {
      '/api': {
        target: 'http://localhost:4000',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
});
