ALTER TABLE "Task" ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "lastRetryAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN "retryHistory" JSONB NOT NULL DEFAULT '[]';
