-- Persist provider routing and execution-budget telemetry on each agent run.
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "providerCalls" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "providerRetries" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "providerRateLimitRetries" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "providerRotations" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "providerLastStatus" INTEGER;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "effectiveModel" TEXT;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "modelsTried" TEXT;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "tokenBudget" INTEGER;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "tokenBudgetExceeded" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "deadlineMs" INTEGER;
ALTER TABLE "AgentRun" ADD COLUMN IF NOT EXISTS "deadlineRemainingMs" INTEGER;
